# This is fantastic! Itemized Python Cells! 


#### This is some of the sub-headers that can be created! 



Tutorial can be found [here](https://www.learnpython.org/)

Along with the Foundations of Applied Mathematics coursework found [here](https://foundations-of-applied-mathematics.github.io/)

#### Intro to Python work: 

In [ ]:
print("Hello World! ")



In [ ]:
name = input("What's your name?:  ")
print("Hello, {}".format(name))

#### Some Variable work: 


In [ ]:
name = "Colin"
print(name)

##### Float Numbers`

In [ ]:
myFloat = 4.0
print(myFloat)
myFloat = float(5)
print(myFloat)

##### String Storage

In [ ]:
someText = "Hello!"
print(someText)

##### multi storage: 


In [ ]:
a,b = 3, 4
print(a,b)

##### Lists! 

In [ ]:
myList = []
myList.append(1)
myList.append(2)
myList.append(3)

print(myList)

#Also, some looping! 


for x in myList:
    print(x)

### Math Time!

In [ ]:
# all the fun features, including modulus(remainder)

sum = 1 + 2
subtract = 2 - 1
multiply = 3 * 3
divide = 21 / 7

#How many times it can divide, and then returns the remainder of the value associated with it.
 
remainder = 24 % 7

print(sum)
print(subtract)
print(multiply)
print(divide)
print(remainder)


#### With Lists: 

In [ ]:
listOne = [1,2,3,4,5]
listTwo = [6,7,8,9,10]

cumulativeList = listOne + listTwo
print(cumulativeList)


In [ ]:
#Multiply: 

listThree = [1,3,5]
print(listThree * 3)

### String Formatting: 


In [ ]:
#Using %s or %d for values to import variables as a string. 


name = "Colin"
print("Hello, %s!" % name)

# This prints out "Colin is 23 years old."
age = 23
print("%s is %d years old." % (name, age))


#Lists can be printed too! 

fruits = ["Apple", "Banana", "Orange"]
print("This is what I found: %s!" % fruits)

In [ ]:
#Strings can have length( len(item))


string = "Hello World"
print(len(string))

b

In [ ]:
#What about indexing items? 

print(string.index('o'))

# Counting number of items? 
print(string.count("o"))

#printing sections of the string can be done by setting a start and end point(Slice) for the characters: 
print(string[3:8])

#Reverse? Set the slice at  [::-1]
print(string[::-1])

#Upper? 
print(string.upper())

#ALSO! Variables can be passed through the notebook


In [ ]:
#String Validation: 

if string == "Hello World" and name == "Colin":
    print("It works! Hello World and Colin are correct")

#### API CALLS! 


In [ ]:
#import requests

#r = requests.get("https://swapi.dev/api/people/1")

#r.status_code
#content = r.content
#print(content)

In [ ]:
#import pandas as pd
#mport requests

#usgsValueAPI = "https://waterservices.usgs.gov/nwis/iv/?format=json&sites=03179000&period=p2d&parameterCd=00060&siteStatus=all"
#values = requests.get(usgsValueAPI)
#print(values.content)

#waterData = pd.read_json(usgsValueAPI)
#print(waterData)


#df_nested_list = pd.json_normalize(usgsValueAPI, record_path=["timeSeries"])



 


In [ ]:
name = "Colin"
print(name.find("li"))

In [ ]:
word = "         bananana"
i = word.find("na") 
print(i)
print(word)
print(word.lstrip())
print(word.rstrip())
print(word)


# Opening a File! 

handle = open()

# Files are read in a sequence of Lines: all broken up by whitespace characters(\n)

## What about files as a sequence: 

handle  = open("filename")

## FOR EACH LINE: PRINT LINE

for variable in handle:
    #print(variable)




In [ ]:
#Opening a File! 

#handle = open()

#Files are read in a sequence of Lines: all broken up by whitespace characters(\n)

#What about files as a sequence: 

#handle  = open("filename")

###FOR EACH LINE: PRINT LINE

#for variable in handle:
    #print(variable)

In [ ]:
#Read the whole file: 

# results = handle.read()b
#print(results)



What about finding things with "From"

In [ ]:
#fhand = open(filename)
#or line in fhand:
 #   if line.startswith("From:" ):
  #      print(line)


#BUT it prints a new line each time! 
#remove whitespace with .rstrip()



### Using Continue!

Continue steps out of current function, goes to next. 

## What about Try and Continue: 

In [ ]:
fname = print(input("Enter file name: "))
try: 
    fopen = open(fname)
except:
    print("File cannot be opened: ", fname)
    quit()


# Lists: 

In [4]:
sampleList = [1,2,3]
print(sampleList[1]) 
print(range(len(sampleList)))

2
range(0, 3)


# Dictionaries! 

#### looks a lot like JS Objects! K-V pairs!

Some common applications: 

In [46]:
names = [ 'quincy', 'mrugesh' , 'beau', "beau"]

#Check if item is in dictionary: 
"colin" in names

#So what happens if it's new? 
counts = dict()
for name in names:
    if name not in counts:
        counts[name] = 1
    else:
        counts[name] = counts[name] + 1
print(counts)


# What about Get? 
# Checking if the key is in there: variable = dictionaryName.get("Key", default)

#False: Expected = 0
nameInDict = counts.get("colin", 0)
print(nameInDict)

# True: expected = 1
nameInDict = counts.get("quincy", 0)
print(nameInDict)

# orrrrrr:
# 
# do the counts this way:  
counts2 = dict()
for name in names: 
    counts2[name] = counts2.get(name, 0) + 1
print(  counts2)
print("list: ", list(counts2))
print("Keys: ", counts2.keys())
print("Values " ,counts2.values())
print("Tuple! ", counts2.items())
        

{'quincy': 1, 'mrugesh': 1, 'beau': 2}
0
1
{'quincy': 1, 'mrugesh': 1, 'beau': 2}
list:  ['quincy', 'mrugesh', 'beau']
Keys:  dict_keys(['quincy', 'mrugesh', 'beau'])
Values  dict_values([1, 1, 2])
Tuple!  dict_items([('quincy', 1), ('mrugesh', 1), ('beau', 2)])


In [47]:
# count things in paragraphs. 

counting = dict()
print("Enter a line of text...")
line = "The quick brown fox jumped over the lazy dog dog"


words = line.split()

print("Words: ", words)

print("Counting...")
for word in words:
    counting[word] = counting.get(word, 0) + 1
print("Counts: ", counting)

print(max(counting, key= counting.get))

        


Enter a line of text...
Words:  ['The', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog', 'dog']
Counting...
Counts:  {'The': 1, 'quick': 1, 'brown': 1, 'fox': 1, 'jumped': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 2}
dog


# Tuples! 


Much like lists: Elements are indexed at 0, accessed by tuple name[index]
print(max(tuple))

## BUTTTTT
Tuples are IMMUTABLE 
cannot alter the contents. no reassignments. Kinda like using const with JS

like y = "ABC" 
y[2] = "D" 
#### ERRORS


x = (1,2,3)
x[2]  = 4
## NOT MODIFIABLE; 

Tuples are more efficient than lists, but are limited. 

Cant sort tuples, cant add to end of tuple, cant change order. 
Basically: Cant modify anything like you could a list. 

## BUT WHY? 

Tuples are useful when making temporary variables. Pretty fast, considering they only have count and index methods. 

## Tuples can have multivariable assignments on left. 

(a,b,c) = (1,2,3)
print(a) = 1

## Can act like dictionaries: 



In [48]:
d = dict()
d["csev"] = 2
d["cwen"] = 3

for (k, v) in d.items():
    print(k, v)

tups = d.items()
print(tups)


csev 2
cwen 3
dict_items([('csev', 2), ('cwen', 3)])


## Comparable:


In [49]:
(0,1,2) > (5,4,3)

False

# Tuples!

Tuples are like lists, but are not mutable and are really quick ways to store limited data. 

Lists have more methods, dir(list_name) vs dir(tuple_name)

Tuples are more efficient, and are faster. 

You can assign multiples with a left-right balance

In [ ]:
test_tuple = (1,2,3)
print(test_tuple.count(1))

#Multiple assignments
(x,y,z) = (0.1, 1, -2)
print(z)

1
-2


### Check this out!

Assign a dictionary to a tuple, and it stores the values internally: 



In [22]:
d = dict()

### key, value
d["21351"] = 101
d["11111"] = 23
d["22222"] = 124
d["12312"] = 0
d["23131"] = 2
d["12372"] = 1
print(d)

sandbox_tuple = d.items()
print(sandbox_tuple)

#Sorted sorts by KEY! NoT VALUE!

print(sorted(sandbox_tuple))


{'21351': 101, '11111': 23, '22222': 124, '12312': 0, '23131': 2, '12372': 1}
dict_items([('21351', 101), ('11111', 23), ('22222', 124), ('12312', 0), ('23131', 2), ('12372', 1)])
[('11111', 23), ('12312', 0), ('12372', 1), ('21351', 101), ('22222', 124), ('23131', 2)]


Functions: 


In [4]:
def sum(x, y):
    return x + y, x - y

sum(3,4)
#also able to extract things: 

# CAn do multiple functions with one call. and unpack returns into different variables. 


a, b = sum(1,2)
print(a,b)




3 -1


# LAMBDA: 

Weird stuff here. Can use lambda to create one line functions: 

eg: 

def f(x):
    return 6x^3 + 2x^2 + (x+1)

into: 

F = lambda x: 6x^3 + 2x^2 + (x+1)


ONLY USE LAMBDA ON SIMPLE OR INTUITIVE FUNCTIONS. 





In [7]:
#Make sure to have returns for things that you want variable assignments for. 

def oops(i):
 print(i + 1)

def increment(i):
 return i + 1

x = oops(1999) # x contains 'None' since oops()
y = increment(1999)
print(x, y)

2000
None 2000


Problem 3. The volume of a sphere with radius r is V =
4
3
πr3
. In your Python file from
Problem 2, define a function called sphere_volume() that accepts a single parameter r. Return
the volume of the sphere of radius r, using 3.14159 as an approximation for π (for now). Also
write an appropriate docstring for your function.
To test your function, call it under the if __name__ == '__main__': clause and print
the returned value. Run your file to see if your answer is what you expect it to be.


In [15]:
def sphere_volume(radius):
    pi = 3.14
    return (4/3)*pi*(radius**3)

sphere_volume(3)

113.03999999999999

It works! Google says 113.1 for radius. 

# NUMPY TIME!


In [14]:
import numpy as np

array = np.array([8,4,6,0,2])
print(array, "is a 1-D Array")

#What about 2-d Arrays?

two_dimension_array = np.array( [ [0,1,2] ,[3,4,5] ] )
#NEEDS EXTRA BRACKET AROUND ARRAY
 

print(two_dimension_array)

[8 4 6 0 2] is a 1-D Array
[[0 1 2]
 [3 4 5]]


Problem #4! 

There are two main ways to perform matrix multiplication in NumPy: with
NumPy’s dot() function (np.dot(A, B)), or with the @ operator (A @ B). Write a function
that defines the following matrices as NumPy arrays.


In [28]:
array1 = np.array([[3, -1, 4], [1, 5, -9]])


array2 = np.array([[2,6,-5,3], [5,-8,9,7],[9,-3,-2,-3]])

print(array1, array2)

def prob4(array1, array2):
    return (array1 @ array2)

prob4(array1, array2)

[[ 3 -1  4]
 [ 1  5 -9]] [[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3 -2 -3]]


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

### NUMPY handles operators slighly different: 

So + concatenates things, and * concatenates a list with self n number of times

NUMPY uses things like matrices and Vectors for things, meaning that mathematical operations are handled slightly different than in JS. 


Problem #5!

Write a function called tax_liability() that accepts a single parameter, income, and
returns the tax liability. To keep this problem simple, assume the individual is always single,
and only use the three tax brackets discussed here (so everything above $85,525 will still be
taxed at the 22% rate).

+ first bracket: 0 => $9875 10%
+ second bracket: $9876 -> $40,125 12%
+ third bracket: $40,126 -> $85,525 22%



In [2]:
def tax_liability(income):
    tax_total = 0
    first_bracket = 9875
    second_bracket = 40125
    #third_bracket = 85525

    first_bracket_tax_rate = .1
    second_bracket_tax_rate = .12
    third_bracket_tax_rate = .22

    if (income <= first_bracket):
        tax_total = income * first_bracket_tax_rate
    elif( income > first_bracket and income <= second_bracket):
        tax_total = (first_bracket * first_bracket_tax_rate) + ( (income - first_bracket) * second_bracket_tax_rate)
    elif( income > second_bracket):
        tax_total = ((first_bracket * first_bracket_tax_rate) + ( (income - first_bracket) * second_bracket_tax_rate)) + ((income - first_bracket - second_bracket) * third_bracket_tax_rate)

    return tax_total

tax_liability(40125)

    
    

4617.5

# Problem 6.
 Now that we have seen how to use lists and NumPy arrays, let’s compare their
abilities. Below are vectors A and B, write a function called prob6a() that defines them using
the Python list data type. Use list comprehension to define the vectors. Return A · B, A + B,
and 2A.
In a separate function called prob6b() define A and B as NumPy arrays and return the
A · B, A + B, and 5A.

A = [1 2 3 4 5 6 7 ]
B = [5 5 5 5 5 5 5 ]


In [37]:
import numpy as np


list1 = [1, 2, 3, 4, 5, 6, 7 ]
list2 = [5, 5, 5, 5, 5, 5, 5 ]


#original function: seems legit.
def prob6a(a, b):
    # make an empty list to store values in multiplication across lists.  
    multiples = []

    #For loop it! 
    for num1, num2 in zip(a,b):
        multiples.append(num1 * num2)

    sum_of_lists = a + b

    #make multiples of exact same list, N number of times. 
    two_times = 2 * a

    return multiples,  sum_of_lists, two_times





def prob6b(a, b):
    #little conversion here

    npArray1 = np.array(a)
    npArray2 = np.array(b)

    #Using different Numpy methods to achieve the same thing: using multiply for multiplying lists
    np_multiplication = np.multiply(npArray1, npArray2)

    #Numpy add for adding array items across the lists: 
    np_sum = np.add(npArray1, npArray2)
    #Tile does something similar to multiplying against an array and just getting the array values copied x number of times. 
    # Could also use np.array(listName * number of times to multiply)
    np_two_times = np.tile(npArray1, 2)

    return np_multiplication, np_sum, np_two_times

prob6a(list1, list2)
prob6b(list1, list2)



([5, 10, 15, 20, 25, 30, 35],
 [1, 2, 3, 4, 5, 6, 7, 5, 5, 5, 5, 5, 5, 5],
 [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

# Chapter 2! 
- The power of a question mark "?"


Need to check out a function for a built in? use function/method name followed by a question mark: ? 